firebase:
  type: service_account
  project_id: kicks-ea7b4
  private_key_id: ${env.FIREBASE_PRIVATE_KEY_ID}
  private_key: ${env.FIREBASE_PRIVATE_KEY}
  client_email: ${env.FIREBASE_CLIENT_EMAIL}
  client_id: ${env.FIREBASE_CLIENT_ID}
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-do73m%40kicks-ea7b4.iam.gserviceaccount.com