spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${env.KAKAO_CLIENT_ID}
            client-name: Kakao
            redirect-uri: ${env.KAKAO_REDIRECT_URI}
            redirect-url: ${env.KAKAO_REDIRECT_URL}
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${env.SMTP_USERNAME}
    password: ${env.SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  secretKey: ${env.JWT_SECRET_KEY}
  refreshKey: ${env.JWT_REFRESH_KEY}

