spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${env.DB_URL}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
    hikari:
      maximum-pool-size: 20

  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB